config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories
  resources :products
  resources :akciis
  resources :akciis
  resources :photobooks
  resources :baners
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'sessions/destroy'

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :panels
  resources :users
  resources :hostmoykas
  resources :hostlishnees
  resources :hostpodzamenus
  resources :hostvremies
  resources :hostmaslos
  resources :hostcoffes
  resources :hostgaranties
  resources :hostmaps
  resources :certobsluzhis
  resources :certelectros
  resources :certpodveskas
  resources :certkapitals
  resources :evakuators
  resources :dozopravkas
  resources :luboyrodremonta
  resources :monitorings
  resources :shinniyservices
  resources :kachestvomoykas
  resources :obsluzhivanies
  resources :kapitalremonts
  resources :zamenamaslos
  resources :mehanicposts
  resources :noteposts
  resources :newposts
  resources :articles
  resources :news

  root 'welcome#index'
  get 'welcome/index'

end

app/models/akcii.rb
class Akcii < ActiveRecord::Base
	dragonfly_accessor :image
end

app/models/article.rb
class Article < ActiveRecord::Base
	dragonfly_accessor :image 
end

app/models/baner.rb
class Baner < ActiveRecord::Base
	dragonfly_accessor :image
end

app/models/category.rb
class Category < ActiveRecord::Base
	dragonfly_accessor :image 
	has_many :products, dependent: :destroy
end

app/models/certelectro.rb
class Certelectro < ActiveRecord::Base
end

app/models/certkapital.rb
class Certkapital < ActiveRecord::Base
end

app/models/dozopravka.rb
class Dozopravka < ActiveRecord::Base
end

app/models/evakuator.rb
class Evakuator < ActiveRecord::Base
end

app/models/hostcoffe.rb
class Hostcoffe < ActiveRecord::Base
end

app/models/hostmap.rb
class Hostmap < ActiveRecord::Base
end

app/models/hostmaslo.rb
class Hostmaslo < ActiveRecord::Base
end

app/models/hostmoyka.rb
class Hostmoyka < ActiveRecord::Base
end

app/models/hostvremy.rb
class Hostvremy < ActiveRecord::Base
end

app/models/mehanicpost.rb
class Mehanicpost < ActiveRecord::Base
end

app/models/monitoring.rb
class Monitoring < ActiveRecord::Base
end

app/models/newpost.rb
class Newpost < ActiveRecord::Base
end

app/models/notepost.rb
class Notepost < ActiveRecord::Base
end

app/models/panel.rb
class Panel < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
	has_secure_password
end

app/models/photobook.rb
class Photobook < ActiveRecord::Base
	dragonfly_accessor :image
end

app/models/product.rb
class Product < ActiveRecord::Base
	dragonfly_accessor :image 
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/mehanicposts_controller.rb
class MehanicpostsController < ApplicationController
  before_action :set_mehanicpost, only: [:show, :edit, :update, :destroy]

  # GET /mehanicposts
  # GET /mehanicposts.json
  def index
    @mehanicposts = Mehanicpost.all
  end

  # GET /mehanicposts/1
  # GET /mehanicposts/1.json
  def show
  end

  # GET /mehanicposts/new
  def new
    @mehanicpost = Mehanicpost.new
  end

  # GET /mehanicposts/1/edit
  def edit
  end

  # POST /mehanicposts
  # POST /mehanicposts.json
  def create
    @mehanicpost = Mehanicpost.new(mehanicpost_params)

    respond_to do |format|
      if @mehanicpost.save
        format.html { redirect_to @mehanicpost, notice: 'Mehanicpost was successfully created.' }
        format.json { render :show, status: :created, location: @mehanicpost }
      else
        format.html { render :new }
        format.json { render json: @mehanicpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mehanicposts/1
  # PATCH/PUT /mehanicposts/1.json
  def update
    respond_to do |format|
      if @mehanicpost.update(mehanicpost_params)
        format.html { redirect_to @mehanicpost, notice: 'Mehanicpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @mehanicpost }
      else
        format.html { render :edit }
        format.json { render json: @mehanicpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mehanicposts/1
  # DELETE /mehanicposts/1.json
  def destroy
    @mehanicpost.destroy
    respond_to do |format|
      format.html { redirect_to mehanicposts_url, notice: 'Mehanicpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mehanicpost
      @mehanicpost = Mehanicpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mehanicpost_params
      params.require(:mehanicpost).permit(:title, :description, :image_url)
    end
end

app/helpers/mehanicposts_helper.rb
module MehanicpostsHelper
end

app/views/mehanicposts/_form.html.erb
<%= form_for(@mehanicpost) do |f| %>
  <% if @mehanicpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mehanicpost.errors.count, "error") %> prohibited this mehanicpost from being saved:</h2>

      <ul>
      <% @mehanicpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mehanicposts/edit.html.erb
<h1>Editing Mehanicpost</h1>

<%= render 'form' %>

<%= link_to 'Show', @mehanicpost %> |
<%= link_to 'Back', mehanicposts_path %>

app/views/mehanicposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mehanicposts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mehanicposts.each do |mehanicpost| %>
      <tr>
        <td><%= mehanicpost.title %></td>
        <td><%= mehanicpost.description %></td>
        <td><%= mehanicpost.image_url %></td>
        <td><%= link_to 'Show', mehanicpost %></td>
        <td><%= link_to 'Edit', edit_mehanicpost_path(mehanicpost) %></td>
        <td><%= link_to 'Destroy', mehanicpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mehanicpost', new_mehanicpost_path %>

app/views/mehanicposts/new.html.erb
<h1>New Mehanicpost</h1>

<%= render 'form' %>

<%= link_to 'Back', mehanicposts_path %>

app/views/mehanicposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @mehanicpost.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @mehanicpost.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @mehanicpost.image_url %>
</p>

<%= link_to 'Edit', edit_mehanicpost_path(@mehanicpost) %> |
<%= link_to 'Back', mehanicposts_path %>