config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories
  resources :products
  resources :akciis
  resources :akciis
  resources :photobooks
  resources :baners
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'sessions/destroy'

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :panels
  resources :users
  resources :hostmoykas
  resources :hostlishnees
  resources :hostpodzamenus
  resources :hostvremies
  resources :hostmaslos
  resources :hostcoffes
  resources :hostgaranties
  resources :hostmaps
  resources :certobsluzhis
  resources :certelectros
  resources :certpodveskas
  resources :certkapitals
  resources :evakuators
  resources :dozopravkas
  resources :luboyrodremonta
  resources :monitorings
  resources :shinniyservices
  resources :kachestvomoykas
  resources :obsluzhivanies
  resources :kapitalremonts
  resources :zamenamaslos
  resources :mehanicposts
  resources :noteposts
  resources :newposts
  resources :articles
  resources :news

  root 'welcome#index'
  get 'welcome/index'

end

app/models/akcii.rb
class Akcii < ActiveRecord::Base
	dragonfly_accessor :image
end

app/models/article.rb
class Article < ActiveRecord::Base
	dragonfly_accessor :image 
end

app/models/baner.rb
class Baner < ActiveRecord::Base
	dragonfly_accessor :image
end

app/models/category.rb
class Category < ActiveRecord::Base
	dragonfly_accessor :image 
	has_many :products, dependent: :destroy
end

app/models/certelectro.rb
class Certelectro < ActiveRecord::Base
end

app/models/certkapital.rb
class Certkapital < ActiveRecord::Base
end

app/models/dozopravka.rb
class Dozopravka < ActiveRecord::Base
end

app/models/evakuator.rb
class Evakuator < ActiveRecord::Base
end

app/models/hostcoffe.rb
class Hostcoffe < ActiveRecord::Base
end

app/models/hostlishnee.rb
class Hostlishnee < ActiveRecord::Base
end

app/models/hostmap.rb
class Hostmap < ActiveRecord::Base
end

app/models/hostmaslo.rb
class Hostmaslo < ActiveRecord::Base
end

app/models/hostmoyka.rb
class Hostmoyka < ActiveRecord::Base
end

app/models/hostvremy.rb
class Hostvremy < ActiveRecord::Base
end

app/models/monitoring.rb
class Monitoring < ActiveRecord::Base
end

app/models/newpost.rb
class Newpost < ActiveRecord::Base
end

app/models/notepost.rb
class Notepost < ActiveRecord::Base
end

app/models/panel.rb
class Panel < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
	has_secure_password
end

app/models/photobook.rb
class Photobook < ActiveRecord::Base
	dragonfly_accessor :image
end

app/models/product.rb
class Product < ActiveRecord::Base
	dragonfly_accessor :image 
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/hostmoykas_controller.rb
class HostmoykasController < ApplicationController
  before_action :set_hostmoyka, only: [:show, :edit, :update, :destroy]

  # GET /hostmoykas
  # GET /hostmoykas.json
  def index
    @hostmoykas = Hostmoyka.all
  end

  # GET /hostmoykas/1
  # GET /hostmoykas/1.json
  def show
  end

  # GET /hostmoykas/new
  def new
    @hostmoyka = Hostmoyka.new
  end

  # GET /hostmoykas/1/edit
  def edit
  end

  # POST /hostmoykas
  # POST /hostmoykas.json
  def create
    @hostmoyka = Hostmoyka.new(hostmoyka_params)

    respond_to do |format|
      if @hostmoyka.save
        format.html { redirect_to @hostmoyka, notice: 'Hostmoyka was successfully created.' }
        format.json { render :show, status: :created, location: @hostmoyka }
      else
        format.html { render :new }
        format.json { render json: @hostmoyka.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hostmoykas/1
  # PATCH/PUT /hostmoykas/1.json
  def update
    respond_to do |format|
      if @hostmoyka.update(hostmoyka_params)
        format.html { redirect_to @hostmoyka, notice: 'Hostmoyka was successfully updated.' }
        format.json { render :show, status: :ok, location: @hostmoyka }
      else
        format.html { render :edit }
        format.json { render json: @hostmoyka.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hostmoykas/1
  # DELETE /hostmoykas/1.json
  def destroy
    @hostmoyka.destroy
    respond_to do |format|
      format.html { redirect_to hostmoykas_url, notice: 'Hostmoyka was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hostmoyka
      @hostmoyka = Hostmoyka.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hostmoyka_params
      params.require(:hostmoyka).permit(:title, :description)
    end
end

app/helpers/hostmoykas_helper.rb
module HostmoykasHelper
end

app/views/hostmoykas/_form.html.erb
<%= form_for(@hostmoyka) do |f| %>
  <% if @hostmoyka.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hostmoyka.errors.count, "error") %> prohibited this hostmoyka from being saved:</h2>

      <ul>
      <% @hostmoyka.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hostmoykas/edit.html.erb
<h1>Editing Hostmoyka</h1>

<%= render 'form' %>

<%= link_to 'Show', @hostmoyka %> |
<%= link_to 'Back', hostmoykas_path %>

app/views/hostmoykas/index.html.erb
<p><strong><%= Hostmoyka.find(1).title %></strong></p>
<%= Hostmoyka.find(1).description.html_safe %>

app/views/hostmoykas/new.html.erb
<h1>New Hostmoyka</h1>

<%= render 'form' %>

<%= link_to 'Back', hostmoykas_path %>

app/views/hostmoykas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @hostmoyka.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hostmoyka.description %>
</p>

<%= link_to 'Edit', edit_hostmoyka_path(@hostmoyka) %> |
<%= link_to 'Back', hostmoykas_path %>