config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories
  resources :products
  resources :akciis
  resources :akciis
  resources :photobooks
  resources :baners
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'sessions/destroy'

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :panels
  resources :users
  resources :hostmoykas
  resources :hostlishnees
  resources :hostpodzamenus
  resources :hostvremies
  resources :hostmaslos
  resources :hostcoffes
  resources :hostgaranties
  resources :hostmaps
  resources :certobsluzhis
  resources :certelectros
  resources :certpodveskas
  resources :certkapitals
  resources :evakuators
  resources :dozopravkas
  resources :luboyrodremonta
  resources :monitorings
  resources :shinniyservices
  resources :kachestvomoykas
  resources :obsluzhivanies
  resources :kapitalremonts
  resources :zamenamaslos
  resources :mehanicposts
  resources :noteposts
  resources :newposts
  resources :articles
  resources :news

  root 'welcome#index'
  get 'welcome/index'

end

app/models/akcii.rb
class Akcii < ActiveRecord::Base
	dragonfly_accessor :image
end

app/models/article.rb
class Article < ActiveRecord::Base
	dragonfly_accessor :image 
end

app/models/baner.rb
class Baner < ActiveRecord::Base
	dragonfly_accessor :image
end

app/models/category.rb
class Category < ActiveRecord::Base
	dragonfly_accessor :image 
	has_many :products, dependent: :destroy
end

app/models/certelectro.rb
class Certelectro < ActiveRecord::Base
end

app/models/certkapital.rb
class Certkapital < ActiveRecord::Base
end

app/models/dozopravka.rb
class Dozopravka < ActiveRecord::Base
end

app/models/evakuator.rb
class Evakuator < ActiveRecord::Base
end

app/models/hostcoffe.rb
class Hostcoffe < ActiveRecord::Base
end

app/models/hostlishnee.rb
class Hostlishnee < ActiveRecord::Base
end

app/models/hostmap.rb
class Hostmap < ActiveRecord::Base
end

app/models/hostmaslo.rb
class Hostmaslo < ActiveRecord::Base
end

app/models/hostmoyka.rb
class Hostmoyka < ActiveRecord::Base
end

app/models/hostvremy.rb
class Hostvremy < ActiveRecord::Base
end

app/models/monitoring.rb
class Monitoring < ActiveRecord::Base
end

app/models/newpost.rb
class Newpost < ActiveRecord::Base
end

app/models/notepost.rb
class Notepost < ActiveRecord::Base
end

app/models/panel.rb
class Panel < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
	has_secure_password
end

app/models/photobook.rb
class Photobook < ActiveRecord::Base
	dragonfly_accessor :image
end

app/models/product.rb
class Product < ActiveRecord::Base
	dragonfly_accessor :image 
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/akciis_controller.rb
class AkciisController < ApplicationController
  before_action :set_akcii, only: [:show, :edit, :update, :destroy]

  # GET /akciis
  # GET /akciis.json
  def index
    @akciis = Akcii.all
  end

  # GET /akciis/1
  # GET /akciis/1.json
  def show
  end

  # GET /akciis/new
  def new
    @akcii = Akcii.new
  end

  # GET /akciis/1/edit
  def edit
  end

  # POST /akciis
  # POST /akciis.json
  def create
    @akcii = Akcii.new(akcii_params)

    respond_to do |format|
      if @akcii.save
        format.html { redirect_to @akcii, notice: 'Akcii was successfully created.' }
        format.json { render :show, status: :created, location: @akcii }
      else
        format.html { render :new }
        format.json { render json: @akcii.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /akciis/1
  # PATCH/PUT /akciis/1.json
  def update
    respond_to do |format|
      if @akcii.update(akcii_params)
        format.html { redirect_to @akcii, notice: 'Akcii was successfully updated.' }
        format.json { render :show, status: :ok, location: @akcii }
      else
        format.html { render :edit }
        format.json { render json: @akcii.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /akciis/1
  # DELETE /akciis/1.json
  def destroy
    @akcii.destroy
    respond_to do |format|
      format.html { redirect_to akciis_url, notice: 'Akcii was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_akcii
      @akcii = Akcii.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def akcii_params
      params.require(:akcii).permit(:title, :description, :image_uid)
    end
end

app/helpers/akciis_helper.rb
module AkciisHelper
end

app/views/akciis/_form.html.erb
<%= form_for(@akcii) do |f| %>
  <% if @akcii.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@akcii.errors.count, "error") %> prohibited this akcii from being saved:</h2>

      <ul>
      <% @akcii.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image_uid %><br>
    <%= f.text_field :image_uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/akciis/edit.html.erb
<h1>Editing Akcii</h1>

<%= render 'form' %>

<%= link_to 'Show', @akcii %> |
<%= link_to 'Back', akciis_path %>

app/views/akciis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Akciis</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @akciis.each do |akcii| %>
      <tr>
        <td><%= akcii.title %></td>
        <td><%= akcii.description %></td>
        <td><%= akcii.image_uid %></td>
        <td><%= link_to 'Show', akcii %></td>
        <td><%= link_to 'Edit', edit_akcii_path(akcii) %></td>
        <td><%= link_to 'Destroy', akcii, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Akcii', new_akcii_path %>

app/views/akciis/new.html.erb
<h1>New Akcii</h1>

<%= render 'form' %>

<%= link_to 'Back', akciis_path %>

app/views/akciis/show.html.erb
<p><strong>АКЦИЯ НАШЕГО АВТОТЕХЦЕНТРА</strong></p>

<div class="content-product-block-out">
<div class="content-img-block" style="width:350px;">
	<%= image_tag @akcii.image.url, width: '350x240', alt: @akcii.title %><%= @akcii.title %><br>
</div>
<p><strong><%= @akcii.title %></strong></p>
<p><%= @akcii.description.html_safe %></p>
</div>
&nbsp<br>